all:
	javac -cp ../../data_structures/Classes/:../../test_util/Classes:./Classes/ -d ./Classes Lca.java 
	javac -cp ../../data_structures/Classes/:../../test_util/Classes:./Classes/ -d ./Classes Main.java 
check: all
	java -cp ../../data_structures/Classes/:../../test_util/Classes:./Classes/ Main 
check-verbose: all
	java -cp ../../data_structures/Classes/:../../test_util/Classes:./Classes/ Main -v

