all:
	javac -cp ../Classes/:. -d ../Classes Tree.java
	javac -cp ../Classes/:. -d ../Classes ./Ordered/OrderedTree.java 
	javac -cp ../Classes/:. -d ../Classes ./Ordered/BinTree.java 
	javac -cp ../Classes/:. -d ../Classes ./Unordered/UnorderedTree.java 
	javac -cp ../Classes/:. -d ../Classes ./TreeUtil.java 
	
